### ISSUE TITLE
Add printed date

### ISSUE THREAD

**Issue by khosh** [Leeiio/printdo#12]
I want to check when the todo list is printed because we cannot understand when is today, tomorrow,  this week or next week.

**Comment by khosh** [comment]
I fixed in my repository.

**Comment by Leeiio** [comment]
Thank you man, i have resigned from the Doit.im and have a long trip these days. I will check your comments in a short time.

**Comment by khosh** [comment]
Dear Leeiio,
Thank you for your reply. 
I modified only "print_unpack.js". I have not update "print.js" using packer.
